
public class FirstCode
{
    public static void main(String[] args)
    {

        System.out.println("Hello world"); // this statement to print or display the data on the monitor

    }

}
/*
 concept of jshell= it is a java shell tool that allows you to execute java codes snippets and see the results immediately
 1.open terminal
 2.type jshell
 3. we can preform simple operations like eg : addition of two numbers using jshell or printing a statement 
 4. it will return the output
 */

 /*
  use terminal to compile and then run the code
  first compile the code and then run the code 
  to compile type "javac" and  then mention the filename.java press enter
  for eg : javac Hello.java
  and then to run the code type "java filename"
  syntax:
  javac classname.java
  java classname
 When we compile and run the program we get a class file which is the byte code  
 lets understand with the help of a flowchart
 [java code] -> [compiler] -> [byte code]


 * compiler is the program which converts the written or translates source code written in a high-level programming language into a machine code
   that can be executed directly by a computer's memory.


 * Byte code is the extra class file generated at the time of execution it is a form of intermediate code that is generated by a compiler it
   is called  as "byte code because it is composed of bytes of codes that can be executed by a virtual machine or runtime environment"



   ********************* to make the code look clean or rearrange the code and optimize the imports press alt+shift+ctrl+l*******************


   */